### ISSUE TITLE
[epic] v1 of Notifications Service

### ISSUE THREAD

**Issue by rufuspollock** [datopian/data-subscriptions#1]
When I am interested in a given dataset I want to get notifications (in a dashboard, via email etc) when that dataset is updated (or other changes happen) so that I can take action e.g. update my application, check if security issue etc

**Design** (including domain model and flows): See README

## Tasks

* [x] User accounts
  * [x] Register
  * [x] Login
  * [x] API key flow
  * [x] Store user info in cookies/local storage
  * [x] Authorization (???) => expose authorization info via api call in CKAN Classic + send api key in calls from frontend
  * [x] Tests (unit/integration)
* [x] Setup new API service
  * [x] Generate and do basic configuration of a new project (Python)
  * [x] Configure basic test suite
  * [x] Configure CI/CD
  * [x] Setup test + development databases
  * [x] Create tables and basic data integrity checks according to specification for other stories
  * [ ] Create seed data and document commands to run
  * [x] Document how to set it up or create a self-documenting Dockerfile
* [ ] Create API endpoints
  * [x] CREATE/UPDATE `POST /subscription` with status. Inserts in the database to create a new dataset subscription for the user.
  * [x] SHOW `GET /subscription` with status. Returns current subscription status(es).
  * [x] DESTROY `DELETE /subscription`. Cancels given subscriptions.
  * [ ] UI. It includes the tasks of coming up with a simple solution based on references.
  * [x] Tests (unit/integration).
* [ ] Setup email service
  * [ ] Choose one based on the requirements. Should include the reasoning behind the choice.
  * [ ] Setup the service with multiple environments (dev, staging, production)
  * [ ] Perform manual tests to ensure everything is setup
  * [ ] Document how to use the service e.g., where to get an API key from a newly created account
* [ ] Create notification orquestrator service to run background tasks after API calls
  * [ ] Generate and do basic configuration of a new project
  * [ ] Configure basic test suite
  * [ ] Configure CI/CD
  * [ ] Setup test + development databases
* [ ] Configure background tasks orquestrator
  * [ ] Choose library/technology to run async tasks (something like http://www.celeryproject.org/)
  * [ ] Configure it as needed
  * [ ] Document how to set it up or create a self-documenting Dockerfile
* [ ] Create notification orquestrator API endpoints
  * [ ] ...

Implement basic parts of the core components

* API service (+ DB)
  * [ ] Spec out
  * [ ] How to implement (2 options: a) do as a CKAN Classic extension b) roll our own microservice). Either is quite easy.
* Emailer Service
  * [ ] Select an emailer service (e.g. twilio sendgrid)
  * [ ] Configure (testing, staging, production environments)
* [ ] Notification Orchestrator: a) EventStream subscriber b) rules to action on those c) Orchestrate sending
  * [ ] Spec it out
  * [ ] Decide about queue

Then do tasks by feature e.g.

### Subscribe via Frontend

* [ ] subscribe API (`POST /subscriptions`)
* [ ] ...

### API service specification

* `subscriptions`: GET, CREATE, UPDATE, DELETE
* `nonsubscribable`: 
  * authz: to be discussed. Obviously sysadmins but maybe also dataset owners (?)
* `notification_settings` (name tbd): per account notification settings
* `templates` (or `admin_settings`)

**Comment by rufuspollock** [comment]
FIXED. This all got implemented and released in June. See README.
